name: Run Guide

on:
  push:
    branches:
      - main

jobs:
  run-guide:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run uv sync
        run: uv sync

      - name: Run guide-cli in Japanese
        run: uv run guide-cli japanese